#-------------------------------
# Site Settings
title: Whispers in Ink
description: |
  Whispers in Ink
  A gentle symphony of thoughts, feelings, and reflections etched onto the canvas of time.
  Whispers in Ink is where fleeting ideas find permanence and untold stories come to life.
  Here, every word carries the weight of meaning, offering a window into the soul, a pause for thought, and a spark for imagination.
  This is a space where silence speaks and ink whispers truths untamed.
logo: "/images/logo.png"
logo_dark: # If you want to add a logo for a dark theme.
color_scheme: light # You can choose three modes auto, light, and dark. By default, the auto mode is set, which means the user can choose the light or dark mode themself.

#-------------------------------
# Navigation Settings
menu_settings:
  menu_items:
    - title: "Home"
      url: "/"
    - title: "Journal"
      url: "/latest/"
    # - title: "Authors"
      # url: "/authors/"
    - title: "Explore"
      submenu:
      - url: "/tags/"
        title: "Topics"
      - url: "/featured/"
        title: "Featured"
      # - url: "/videos/"
        # title: "Videos"
      # - url: "/elements/"
        # title: "Elements"
    - title: "About"
      url: "/about/"

# Call to action button
cta_button:
  enable: true
  cta_button_link: '/contact/'
  cta_button_text: Get in touch


#-------------------------------
# Hero Settings
hero:
  enable: true
  hero_title: Whispers in Ink
  hero_description: Step into a journey of discovery - where curiosity leads, and insights unfold for those seeking depth and meaning.

hero_authors:
  enable: false # IM THE ONLY AUTHOR, LOL
  hero_authors_description: Meet our talented team


#-------------------------------
# Blog Section Settings
blog:
  enable: true
  blog_title: Latest


#-------------------------------
# Recommended Section Settings
recommended:
  enable: true
  recommended_title: Recommended
  recommended_tag: "Rumination"


#-------------------------------
# About Section Settings
about:
  enable: true
  about_title: Hello, I’m Aman
  about_subtitle: I’m a thinker and storyteller with a passion for exploring life’s deeper questions, blending philosophy with creativity to seek meaning in the modern world.
  about_description: |
    My journey is guided by a belief that true understanding can transform how we see ourselves and others. Through this space, I bridge the realms of thought, art, and technology, offering reflections that inspire introspection and cultivate curiosity.
    
    This blog is more than words; it’s a journey into ideas that challenge the ordinary, expand the boundaries of what we perceive, and invite us to engage with life more profoundly. Each post is an invitation to pause, reflect, and grow, in a space where insight and discovery intertwine.
  about_image: "/images/aman.jpg"
  about_image_alt: 
  about_button_text: My story
  about_button_link: "/about/"


#-------------------------------
# Authors Section Settings
authors:
  enable: false
  authors_title: Top authors


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp_title: Stay Inspired Weekly. Your Friendly Dose of Insights!
  mailchimp_description: Every Sunday, I deliver actionable tips for enhancing productivity, practical life advice, and top-notch insights gathered from various sources, right to your email inbox.
  mailchimp_identifier: gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp # Add your MailChimp form identifier. For example - gmail.us21.list-manage.com/subscribe/post?u=8aeb9c31a5c97a3a5f9ff2740&amp;id=0e31fd7793&amp
  mailchimp_input_text: Your email address
  mailchimp_button_text: Subscribe


#-------------------------------
# Footer Settings
footer_description: Like the gentle glow of moonlight illuminating a quiet path, this blog aims to shed light on ideas that might otherwise remain in the shadows.


# Social Links
social:
- {icon: "fa-brands fa-linkedin", name: "LinkedIn", link: "https://www.linkedin.com/in/aman-gudluri/"}
# - {icon: "fa-brands fa-facebook-f", name: "Facebook", link: "https://facebook.com"}
# - {icon: "fa-brands fa-x-twitter", name: "Twitter", link: "https://twitter.com"}
# - {icon: "fa-brands fa-tiktok", name: "Tiktok", link: "https://www.tiktok.com"}
# - {icon: "fa-brands fa-instagram", name: "Instagram", link: "https://instagram.com"}
# - {icon: "fa-brands fa-mastodon", name: "Mastodon", link: "https://mastodon.social"}
# - {icon: "fa-brands fa-dribbble", name: "Dribbble", link: "https://www.dribbble.com"}

# Example of adding a new link to the footer - {icon: "fa-brands fa-youtube", name: "Youtube", link: https://youtube.com"}
# Other icons can be found at https://fontawesome.com/icons


#-------------------------------
# Contact Settings
contact:
  form_id: amangudluri@yahoo.com # Add your form_id
  title: Contact Us
  description: I'd love to hear from you!
  button_text: Send now

# NOTE
# Nomod theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. 
# Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus_identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google_analytics: # Add your GA Tracking Id